import { useParams, Link } from "wouter";
import { useReport } from "@/hooks/use-reports";
import { Layout } from "@/components/Layout";
import { 
  AlertTriangle, 
  CheckCircle2, 
  ArrowLeft, 
  Activity, 
  Apple, 
  Dumbbell, 
  Stethoscope,
  Info
} from "lucide-react";
import { motion } from "framer-motion";

export default function Report() {
  const { id } = useParams<{ id: string }>();
  const reportId = Number(id);
  const { data: report, isLoading, isError } = useReport(reportId);

  if (isLoading) {
    return (
      <Layout>
        <div className="max-w-5xl mx-auto px-4 py-12">
          <div className="animate-pulse space-y-8">
            <div className="h-8 bg-muted rounded w-1/4"></div>
            <div className="h-32 bg-muted rounded-2xl"></div>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="h-64 bg-muted rounded-2xl"></div>
              <div className="h-64 bg-muted rounded-2xl"></div>
            </div>
          </div>
        </div>
      </Layout>
    );
  }

  if (isError || !report) {
    return (
      <Layout>
        <div className="max-w-3xl mx-auto px-4 py-24 text-center">
          <div className="bg-destructive/10 text-destructive w-20 h-20 rounded-full flex items-center justify-center mx-auto mb-6">
            <AlertTriangle className="w-10 h-10" />
          </div>
          <h2 className="text-3xl font-display font-bold mb-4">Report Not Found</h2>
          <p className="text-muted-foreground mb-8">We couldn't load the requested report. It may have been deleted or the link is invalid.</p>
          <Link href="/" className="inline-flex px-6 py-3 bg-primary text-primary-foreground rounded-xl font-semibold hover:bg-primary/90 transition-colors">
            Upload New Report
          </Link>
        </div>
      </Layout>
    );
  }

  const { metrics } = report;
  const hasAbnormal = metrics.abnormalTests > 0;

  const containerVariants = {
    hidden: { opacity: 0 },
    show: {
      opacity: 1,
      transition: { staggerChildren: 0.1 }
    }
  };

  const itemVariants = {
    hidden: { opacity: 0, y: 20 },
    show: { opacity: 1, y: 0, transition: { duration: 0.4 } }
  };

  return (
    <Layout>
      <div className="max-w-6xl mx-auto px-4 py-8 md:py-12">
        
        {/* Back navigation & Title */}
        <div className="mb-8">
          <Link href="/" className="inline-flex items-center gap-2 text-muted-foreground hover:text-primary font-medium mb-6 transition-colors">
            <ArrowLeft className="w-4 h-4" />
            Back to Upload
          </Link>
          <h1 className="text-3xl md:text-4xl font-display font-bold text-foreground">
            {report.title || "Lab Report Analysis"}
          </h1>
          <p className="text-muted-foreground mt-2 flex items-center gap-2">
            <Activity className="w-4 h-4" /> Analyzed on {new Date(report.createdAt!).toLocaleDateString('en-IN', { dateStyle: 'long' })}
          </p>
        </div>

        {/* Doctor Warning Banner */}
        <motion.div 
          initial={{ opacity: 0, y: -10 }}
          animate={{ opacity: 1, y: 0 }}
          className="bg-amber-50 border-l-4 border-amber-500 rounded-r-2xl p-6 mb-8 flex gap-4 items-start shadow-sm"
        >
          <Stethoscope className="w-6 h-6 text-amber-600 shrink-0 mt-1" />
          <div>
            <h3 className="font-bold text-amber-900 text-lg mb-1">Medical Disclaimer</h3>
            <p className="text-amber-800/80 font-medium">
              This analysis is generated by AI to help you understand your biomarkers. It is <strong>not a substitute for professional medical advice</strong>. Always consult your doctor before making any changes to your diet or medication.
            </p>
          </div>
        </motion.div>

        <motion.div 
          variants={containerVariants}
          initial="hidden"
          animate="show"
          className="space-y-8"
        >
          {/* Executive Summary */}
          <motion.section variants={itemVariants} className="bg-white rounded-3xl p-6 md:p-8 border border-border shadow-lg shadow-black/5">
            <h2 className="text-2xl font-bold font-display flex items-center gap-3 mb-6">
              <Info className="w-6 h-6 text-primary" />
              Executive Summary
            </h2>
            <p className="text-lg leading-relaxed text-foreground/80 font-medium mb-8">
              {report.summary}
            </p>
            
            <div className="grid grid-cols-3 gap-4 md:gap-8 pt-6 border-t border-border">
              <div className="text-center">
                <div className="text-4xl font-display font-bold text-foreground mb-1">{metrics.totalTests}</div>
                <div className="text-sm font-semibold text-muted-foreground uppercase tracking-wider">Total Tests</div>
              </div>
              <div className="text-center">
                <div className="text-4xl font-display font-bold text-secondary mb-1">{metrics.normalTests}</div>
                <div className="text-sm font-semibold text-muted-foreground uppercase tracking-wider">Normal</div>
              </div>
              <div className="text-center">
                <div className="text-4xl font-display font-bold text-destructive mb-1">{metrics.abnormalTests}</div>
                <div className="text-sm font-semibold text-muted-foreground uppercase tracking-wider">Requires Attention</div>
              </div>
            </div>
          </motion.section>

          {/* Test Results Grid */}
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
            
            {/* Abnormal Tests - Priority Focus */}
            <motion.section variants={itemVariants}>
              <div className={`h-full rounded-3xl border ${hasAbnormal ? 'bg-destructive/5 border-destructive/20 shadow-lg shadow-destructive/5' : 'bg-white border-border shadow-md shadow-black/5'} p-6 md:p-8`}>
                <h2 className={`text-2xl font-bold font-display flex items-center gap-3 mb-6 ${hasAbnormal ? 'text-destructive' : 'text-foreground'}`}>
                  {hasAbnormal ? <AlertTriangle className="w-6 h-6" /> : <CheckCircle2 className="w-6 h-6 text-secondary" />}
                  Requires Attention
                </h2>
                
                {hasAbnormal ? (
                  <div className="space-y-4">
                    {metrics.abnormalAlerts.map((alert, idx) => (
                      <div key={idx} className="bg-white rounded-2xl p-5 border border-destructive/10 shadow-sm">
                        <div className="flex justify-between items-start mb-2">
                          <h4 className="font-bold text-lg text-foreground">{alert.name}</h4>
                          <span className="bg-destructive/10 text-destructive px-3 py-1 rounded-full text-sm font-bold">
                            {alert.value} {alert.unit}
                          </span>
                        </div>
                        <p className="text-sm font-medium text-muted-foreground flex items-center gap-2">
                          <span className="w-1.5 h-1.5 rounded-full bg-secondary inline-block"></span>
                          Expected range: <span className="text-foreground font-semibold">{alert.expected} {alert.unit}</span>
                        </p>
                      </div>
                    ))}
                  </div>
                ) : (
                  <div className="text-center py-12 px-4">
                    <div className="w-16 h-16 bg-secondary/10 rounded-full flex items-center justify-center mx-auto mb-4">
                      <CheckCircle2 className="w-8 h-8 text-secondary" />
                    </div>
                    <h3 className="text-xl font-bold mb-2">All Clear!</h3>
                    <p className="text-muted-foreground">None of your tested biomarkers are outside the normal reference ranges.</p>
                  </div>
                )}
              </div>
            </motion.section>

            {/* Normal Tests */}
            <motion.section variants={itemVariants}>
              <div className="h-full bg-white rounded-3xl border border-border shadow-md shadow-black/5 p-6 md:p-8">
                <h2 className="text-2xl font-bold font-display flex items-center gap-3 mb-6 text-foreground">
                  <CheckCircle2 className="w-6 h-6 text-secondary" />
                  Normal Results
                </h2>
                
                {metrics.normalList.length > 0 ? (
                  <div className="space-y-3">
                    {metrics.normalList.map((item, idx) => (
                      <div key={idx} className="flex justify-between items-center p-4 hover:bg-secondary/5 rounded-xl transition-colors border border-transparent hover:border-secondary/10">
                        <span className="font-semibold text-foreground">{item.name}</span>
                        <span className="font-bold text-secondary bg-secondary/10 px-3 py-1 rounded-lg text-sm">
                          {item.value} {item.unit}
                        </span>
                      </div>
                    ))}
                  </div>
                ) : (
                  <p className="text-muted-foreground text-center py-8">No normal results found in this report.</p>
                )}
              </div>
            </motion.section>
          </div>

          {/* Recommendations Grid */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            {/* Diet */}
            <motion.section variants={itemVariants}>
              <div className="h-full bg-gradient-to-br from-green-50 to-emerald-50/20 rounded-3xl border border-green-100 shadow-md shadow-green-900/5 p-6 md:p-8">
                <h2 className="text-2xl font-bold font-display flex items-center gap-3 mb-6 text-green-800">
                  <div className="bg-green-100 p-2 rounded-xl"><Apple className="w-6 h-6 text-green-600" /></div>
                  Dietary Suggestions
                </h2>
                <ul className="space-y-4">
                  {report.dietRecommendations.map((item, idx) => (
                    <li key={idx} className="flex items-start gap-3 text-green-900/80 font-medium">
                      <div className="mt-1.5 w-1.5 h-1.5 rounded-full bg-green-500 shrink-0"></div>
                      <span className="leading-relaxed">{item}</span>
                    </li>
                  ))}
                </ul>
              </div>
            </motion.section>

            {/* Lifestyle & Exercise */}
            <motion.section variants={itemVariants}>
              <div className="h-full bg-gradient-to-br from-blue-50 to-indigo-50/20 rounded-3xl border border-blue-100 shadow-md shadow-blue-900/5 p-6 md:p-8">
                <h2 className="text-2xl font-bold font-display flex items-center gap-3 mb-6 text-blue-800">
                  <div className="bg-blue-100 p-2 rounded-xl"><Dumbbell className="w-6 h-6 text-blue-600" /></div>
                  Lifestyle & Yoga
                </h2>
                <ul className="space-y-4">
                  {report.exerciseRecommendations.map((item, idx) => (
                    <li key={idx} className="flex items-start gap-3 text-blue-900/80 font-medium">
                      <div className="mt-1.5 w-1.5 h-1.5 rounded-full bg-blue-500 shrink-0"></div>
                      <span className="leading-relaxed">{item}</span>
                    </li>
                  ))}
                </ul>
              </div>
            </motion.section>
          </div>

        </motion.div>
      </div>
    </Layout>
  );
}
